<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>Images\CybertoolsLogohammer.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\CyberTools.ico" />
    <None Remove="Images\Cybertools.png" />
    <None Remove="Images\CyberToolsLogo.ico" />
    <None Remove="Images\Mr-robot.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Images\CybertoolsLogohammer.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\CybertoolsLogohammer.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="5.2.1" />
    <PackageReference Include="MaterialDesignThemes" Version="5.2.1" />
    <PackageReference Include="PacketDotNet" Version="1.4.7" />
    <PackageReference Include="SharpPcap" Version="6.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\CyberTools.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\Cybertools.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\" />
    <Folder Include="Theme\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="WifiDeauthLib.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
